co-cddo/data-marketplace

Dockerfile, __tests__/app.test.ts, src/app.ts, src/routes/pagesRoutes.ts, src/routes/shareRoutes.ts, src/views/page.njk
tightens up docker security
includes updates from dev team
=> Docker improvements and development update

__tests__/find.test.ts, src/app.ts, src/routes/findRoutes.ts, src/services/findService.ts, src/views/error.njk, src/views/layouts/base.njk
- Catch-all route error handling.
- Error-handling middleware that gets triggered when .next is called on an erroring function.
- Dynamic .njk page that responds with variable messages passed from the express middleware.
- Add title to layout and dynamically change the title based on error response.
- Mock test endpoint added to test suite beforeEach and afterEach test.
=> DMBM-625/Error handling implementation

src/helperFunctions/helperFunctions.ts, src/routes/acquirerRoutes.ts, src/types/express.d.ts, src/views/acquirer/date.njk
This branch contains both date-required page and data-required page with functionality.
=> DMBM-624/Purposeofthedatashare-date-required

src/helperFunctions/helperFunctions.ts, src/views/acquirer/legal-gateway.njk
- Implemented legal-gateway page
- made it so that whichever radio is selected; the current text field overwrites the last (single decision with explanation)
=> Implemented legal-gateway page

src/helperFunctions/helperFunctions.ts, src/views/acquirer/legal-review.njk
- Implemented legal-review page
=> Implemented legal-review page

src/helperFunctions/helperFunctions.ts, src/routes/acquirerRoutes.ts, src/types/express.d.ts, src/views/acquirer/data-travel-location.njk, src/views/acquirer/lawful-basis-special-public-interest.njk, src/views/acquirer/protection-review.njk
This branch is relate to protection review page
it's being also added hidden pages as data-travel-location and lawful-basis-special-public-interest
=> Dmdb 710/data protection review

src/routes/supplierRoutes.ts, src/stylesheets/application.scss, src/views/supplier/manage-shares.njk, src/views/supplier/received-requests.njk
Implemented the received request page (UI)
=> Dmbm 732/manage received requests

src/routes/acquirerRoutes.ts, src/types/express.d.ts, src/views/acquirer/declaration.njk
Implemented the declaration page in the acquirer journey
=> implemented declaration page - acquirer

src/routes/supplierRoutes.ts, src/stylesheets/application.scss, src/views/supplier/decision.njk
Implemented the decision page for the supplier journey (UI)
=> Dmbm 736/build decision page (UI)

src/routes/supplierRoutes.ts, src/stylesheets/application.scss, src/views/supplier/review-request.njk, src/views/supplier/review-summary.njk
This PR implements the UI for the build review page. This is temporarily just the UI implementation with hardcoded values until we set up received requests logic.
=> DMBM-735 - Build Review Page (UI)

src/routes/supplierRoutes.ts, src/views/supplier/decision.njk, src/views/supplier/declaration.njk
Implement the declaration page of the supplier request journey which shows a summary of the information the supplier is accepting. This screen only appears if the user selects 'Accept data share request' on the previous decision page. The routing is currently temporary until we implement the logic for this form.
=> DMBM-738 - Declaration

src/routes/supplierRoutes.ts, src/stylesheets/application.scss, src/views/supplier/decision.njk, src/views/supplier/return-request.njk
Implemented return request page (UI)
=> DMBM-737/confirmation return request (UI)

src/routes/supplierRoutes.ts, src/stylesheets/application.scss, src/views/supplier/accept-request.njk
=> DMBM-739/confirmation accept request (UI)

src/routes/supplierRoutes.ts, src/services/findService.ts, src/stylesheets/application.scss, src/views/supplier/reject-request.njk, src/views/supplier/return-request.njk
Implemented return reject page (UI)
=> DMBM-740/Implemented rejected request page (UI)

__tests__/learn.tests.ts, src/routes/learnRoutes.ts, src/views/learn/data-sharing-arrangements.njk, src/views/learn/main.njk
This PR adds data sharing arrangements as the prototype: https://dds-e2e.herokuapp.com/WIP/learn/articles/data-sharing-arrangements#1
This is not the final design.
=> Learn data sharing arrangements

package.json, src/routes/learnRoutes.ts, src/routes/supplierRoutes.ts, src/types/express.d.ts
Formatting & linting. Update package.json version
=> Formatting & linting. Update package.json version

src/views/learn/data-sharing-arrangements.njk
Removal of this line: "As an example, you can download the cabinet office data sharing agreement template."
=> DMBM/832 - LEARN - Data sharing arrangements content edit

src/middleware/validateFormMiddleware.ts, src/routes/acquirerRoutes.ts, src/types/express.d.ts, src/views/acquirer/data-subjects.njk, src/views/layouts/base.njk
=> reworks validation

src/routes/supplierRoutes.ts, src/views/supplier/reject-request.njk, src/views/supplier/return-request.njk
Implemented rejected and returned pages for the Received journey  of the manage data share
=> implements rejected and returned pages

__tests__/learnArticles.tests.ts, src/routes/learnArticleRoutes.ts, src/views/learn/main.njk, src/views/learn/sign-in-process.njk
Implemented the "Sign-on-process" LEARN page
shows this page:
=> Dmbm 923/learn add guidance sign in

src/routes/adminRoutes.ts
I've added a Delete User route to the admin routes, in case we need to be able to delete users from the live site.
=> Update admin-only routes

src/helperFunctions/checkhelper.ts, src/helperFunctions/formHelper.ts
This PR change the date format in check answers page
=> format date

src/routes/infoRoutes.ts, src/views/partials/footer.njk, src/views/privacy.njk
This PR is adding Privacy page
PS: Sorry for the weird name of the branch haha
=> add privacy statement

src/routes/infoRoutes.ts, src/views/accessibility.njk, src/views/partials/footer.njk
This PR adds the accessibility statement page, which is accessed via the footer link.
=> Add accessibility statement

src/helperFunctions/checkhelper.ts, src/helperFunctions/formHelper.ts, src/routes/supplierRoutes.ts
In #153 I updated the acquirer form so that the default status is `NOT STARTED`, but I forgot to update the status to `IN PROGRESS` once some changes had been made 🤦 
- Fixed the above, by adding a check in `updateStepsStatus`
- Formatting updates in a couple of other files.
=> Bugfix: Acquirer form status

src/views/publisher/csv_start.njk, src/views/publisher/csv_upload.njk, src/views/publisher/preview.njk, src/views/publisher/upload-summary.njk
=> Publish UI 

__tests__/learnArticles.tests.ts, src/views/learn/main.njk, src/views/learn/metadata-model.njk
=> replace DCAT-link

src/stylesheets/application.scss, src/views/resource.njk
This PR adds the `creator` row in the "Further information" section
Also added `Publisher` row in the "Further infromation" section
=> update resource page

package-lock.json, package.json, src/routes/publisherRoutes.ts, src/routes/supplierRoutes.ts, src/types/express.d.ts, src/views/publisher/bad_spreadsheet.njk, src/views/publisher/csv_upload.njk, src/views/publisher/total_error.njk, src/views/publisher/upload-summary.njk
When you don't have permission to add an asset, we were seeing the asset ID and type "unknown" in the upload summary table because we didn't have an error from the API to construct these values. This fixes it by adding the asset to the error to mimic what we get from the API.
=> More informative errors for unauthorized additions

src/routes/publisherRoutes.ts
When we added the permission check on CSV assets, it did the following things:
1. Show an error in the table that says you don't have permission
2. Hide the "publish" button so the user has to correct the issue
There were two problems with this. Firstly, we ended up showing a row that says "PASS" as well as an error row for each asset that failed permission validation. Secondly, and more concerningly, there was nothing to stop the user publishing things they've no right to publish by going to /publish even if the button that did so was removed.
I have fixed these by removing the offending assets from session.uploadData so the upload summary page behaves in the same way as with other types of validation error
**Note**
None of this actually stops a technically-minded user from publishing to …
=> Prevent publishing assets without permission
