co-cddo/data-marketplace

__tests__/find.test.ts
src/services/findService.ts

Update the fetch methods to use the base URL variable stored in .env and append with `/catalogue`.
Refactor tests to check for this new URL.

Append /catalogue to API endpoint in resource fetch methods

---

src/app.ts
src/routes/loginRoutes.ts

The /logout route removes the jwtToken cookie and redirects to the index.
I thought it made sense that the `/logout` lived in the same file as `/login`, but that meant also having to update the `loginRoutes` router to use `/` as its base path instead of `/login`. 
I'm happy to move `/logout` into its own router if you want to keep `loginRoutes` unchanged

Adds /logout to loginRoutes

---

src/helperFunctions/helperFunctions.ts
src/routes/acquirerRoutes.ts
src/types/express.d.ts
src/views/acquirer/date.njk

I've made some changes to the validation to fix a couple of small issues I spotted.
Even though the errorMessage being passed to the data.njk template was an empty string, an error was still being displayed on the page.
The gov design system documentation says:
> The error message component will not display if you use a falsy value for errorMessage, for example false or null.
So we need to pass something like `false` or `null` as the error message if we want nothing to displayed. I've updated the data.njk template to include: `{% set errorText = ({text: errorMessage} if errorMessage else false) %}` and use that to set the error message.
One issue with doing `res.render` from a `POST` route is that if the user refreshes the page for any reason they'll get a confusing "Confirm form …

Validation updates

---

src/models/shareRequestTemplate.json
src/routes/acquirerRoutes.ts
src/types/express.d.ts
src/views/acquirer/start.njk

There are some steps in the acquirer journey which you can skip, or which you can only get routed to, if you've provided specific answers to previous questions.
For example, if you answer "None" to the `data-type` question you skip the `data-subjects` and `lawful basis` questions.
And if you answer `Yes` to the `data-access` question, you get routed to a hidden page asking for details about the other organisations that will have access to the data.
I've set the steps up so that there's only a single path through the acquirer journey, which goes through every single step. And I've added a `skipThisStep` function that is called in the `GET /acquirer/:assetID/:step` route, which is used decide whether we need to skip over the step that's about to be displayed, based on the form data that is …

DMBM 719 - Hidden page functionality

---

src/helperFunctions/helperFunctions.ts
src/models/shareRequestTemplate.json
src/types/express.d.ts
src/views/acquirer/basis.njk
src/views/acquirer/lawful-basis-personal.njk
src/views/acquirer/lawful-basis-special.njk
src/views/acquirer/legal-gateway.njk
src/views/acquirer/legal-power.njk

- Implemented Data Protection - Basis page
- updated shareRequestTemplate json - basis to have value: [] to allow for multiple checkbox values
Implemented the Lawful Basis Personal and Special page
Implemented type guarding for the existing pages, all of this is done in the extractFormData function.
I have abstracted out the ```  const radioFields = ["data-type", "data-access", "legal-review"];
const textFields = ["impact", "data-subjects", "data-required"];``` into its own type:
```
type TextFieldStepID = "impact" | "data-subjects" | "data-required";
and
type RadioFieldStepID = "data-type" | "data-access" | "legal-review";
```
It's important to note that the step interface here:
```
interface Step {
id: TextFieldStepID | RadioFieldStepID |
name: string;
status: string;
value: StepValue; …
```

Dmbm 707/dataprotection lawful basis for personal data

---

src/routes/acquirerRoutes.ts
src/views/acquirer/legal-gateway-advice.njk
src/views/acquirer/legal-power-advice.njk

- Added legal-power-advice and lega-gateway-advice pages, and the steps in `skipThisStep` to skip over them if necessary.
The [determineNextStep](https://github.com/co-cddo/data-marketplace/blob/DMBM/Legalpowerandgateway_HiddenLegalAdvice/src/routes/acquirerRoutes.ts#L51) function in @AShaww 's branch is another way of doing this.
`determineThisStep` is definitely more flexible, in that it would let you jump from one page of the form to any other. But I don't think we need that flexibility at the moment, and it'd be a pretty complicated form for the users if they were expected to complete it not in start->finish order (it's already pretty complicated with all the hidden pages, but I don't think there are any plans to completely change the flow)

Legal Advice Pages

---

src/helperFunctions/helperFunctions.ts
src/models/shareRequestTemplate.json
src/types/express.d.ts
src/views/acquirer/data-type.njk

Made it so the data-type page uses checkboxes, so we can have multiple values for the skipping pages within the Data Protection section, see here:
I have gone and implemented a DataTypeStep type - with this i have updated the LegalDecision type to GenericDecisions
see here:
and here:
The changes were made to help blockers on routing within the DataProtection section of the acquirer journey

Data-type page now uses checkboxes

---

src/helperFunctions/helperFunctions.ts
src/views/acquirer/data-type.njk

Added exclusive behaviour to data-type "none" checkbox, this makes it so selecting "none" clears "personal" and "special" if selected.
Also refactored data-type case in extractFormData, we don't need to check inputs anymore

Data type behaviour bug fix

---

src/helperFunctions/helperFunctions.ts
src/routes/acquirerRoutes.ts
src/types/express.d.ts
src/views/acquirer/lawful-basis-special-public-interest.njk

In this PR, I've introduced the lawful-basis-special-public-interest page. To access this hidden page, users should select the "none" checkbox and navigate through the legal review page.
Furthermore, I've enriched the formData interface with a stepHistory feature. This ensures continuity in tracking page navigation within the session data.
Process Flow:
The journey starts at the data-type page.
Users progress through the flow based on prior selections.
Each navigational step gets logged into the stepHistory array.
The array accumulates steps until the user clicks on "Save and return".
Clicking "Save and return" clears the stepHistory array since it's no longer required once the user redirects to the overview page.

Dmbm 779/dataprotectionlawfulbasis_specialcategorydata

---

src/helperFunctions/helperFunctions.ts
src/models/shareRequestTemplate.json
src/routes/acquirerRoutes.ts
src/stylesheets/application.scss
src/types/express.d.ts
src/views/acquirer/other-orgs.njk

Initially the prototype would show the "Add another organisation" as an anchor, having tried to implement this and realising if I where to create this as an anchor and set an action in the backend to addOrgs the task would grow much larger as we are customising an anchor instead of a form submit.
After the stand-up 25/08, we the devs settled with having the "Add another organisation" as a button as it would be easier for handling form actions
Backend Handling with addOrgs and removeOrgs
Renaming Type for Clarity: ```type MoreOrganisation = string[]; -> MoreOrganisationStep ``` 
Accessibility Improvements: [design-patterns.service.justice.gov.uk](https://design-patterns.service.justice.gov.uk/components/add-another/) docs, under accessibility it states:
"People with low vision have also …

Implemented other-orgs page

---

src/app.ts
src/routes/supplierRoutes.ts
src/stylesheets/_masthead.scss
src/stylesheets/_navigation.scss
src/views/home.njk
src/views/supplier/manage-shares.njk

Implemented the manage share page
I've noticed that amongst most pages, including the manage-share page all the govuk-links when hovering over would not show the underline. I have implemented the SCSS for this to match the prototype.
[link to styling demo](https://gyazo.com/b0962450e4c359728667abc239dd322c)
Added the backLink for this page, takes the user to '/' home
The navigation bar had a margin-top, removed this to match prototype.

Dmbm 731/manage shares page

---

src/helperFunctions/helperFunctions.ts
src/models/shareRequestTemplate.json
src/routes/acquirerRoutes.ts
src/routes/supplierRoutes.ts
src/stylesheets/_expander.scss
src/stylesheets/application.scss
src/types/express.d.ts
src/views/acquirer/benefits.njk
src/views/acquirer/data-required.njk
src/views/acquirer/data-subjects.njk
src/views/acquirer/data-travel-location.njk
src/views/acquirer/delivery.njk
src/views/acquirer/format.njk
src/views/acquirer/lawful-basis-personal.njk
src/views/acquirer/legal-power.njk

The biggest change in this PR is implementing the functionality in `data-travel-location` if the user selects `Yes, it will leave the UK` on the `data-travel page` to add additional countries as the prototype suggests, this functionality is exactly the same as the "other-orgs" page, where the user is able to add additional strings into an array.
can be seen here [picture of data-travel-location](https://gyazo.com/3bf39e75b3d265652fc6ddab36670d83)
Also instead of creating another type of string[] for `data-travel-location` StepValue I instead changed the `MoreOrganisationStep` type to GenericStringArray and used this generic type for both `other-orgs` and `data-travel-location` steps.
I have gone and implemented these things:
increased padding under filter options within the `find` page …

Acquirer missing UI refactor

---

src/routes/supplierRoutes.ts
src/stylesheets/application.scss
src/views/supplier/received-requests.njk
src/views/supplier/review-summary.njk

Implemented the review-summary page. 
This is the same as the prototype, we can click the initial request id here:
which takes us to the review-summary page:

First implementation of review-summary (UI)

---

package.json
src/helperFunctions/helperFunctions.ts

This PR fixes a bug found by @AShaww where if you tick several of the "lawful basis" checkboxes they all end up on the same line on the Check Page:
Added a line break in between checkbox items.
The page now looks like this:

Check page: lawful basis items

---

tsconfig.json

It's unclear why, but on linux systems we were seeing a build error relating to the default value of "module" being node16 instead of commonjs. This change resolves it by explicitly setting the module. I can't say I know exactly what the module configuration does, but the fix works.

Update tsconfig.json with commonjs module

---

__tests__/find.test.ts
__tests__/mock/mockData.json
__tests__/mock/singleMockData.json
package-lock.json
src/mockData/themes.ts
src/routes/findRoutes.ts
src/services/findService.ts
src/views/find.njk

This PR implements filtering by theme on the search results page by building on the existing implementation of filtering by organisation. There is a hardcoded list of available themes to filter by which are taken from the topic filters on [data.gov.uk](data.gov.uk). The theme filters work in combination with the organisation filters and the search query to display relevant resources. 
I added additional test coverage to test the theme filters with and without combinations with the query and organisation filters.  The [API](https://github.com/co-cddo/data-marketplace-api) we are calling returns an array of strings for the themes which were initially in the format of a URI, however this has now been changed to a readable label instead. The mock data has since been updated to reflect the …

DMBM-78 - Explore by Theme

---

src/routes/supplierRoutes.ts
src/views/supplier/received-requests.njk
src/views/supplier/request-accepted.njk

Add the UI for request-accepted page.
In the received-requests page there's a ID with link for the completed request
The data is hard coded

add request accept page

---

src/routes/supplierRoutes.ts
src/types/express.d.ts
src/views/supplier/created-requests.njk

Implemented the empty state text for the created requests page:
This PR only has the created request empty state text, currently the received requests have hardcoded values and no functionality yet to retrieve data.
When there is some functionality for the received side we have something to work with.

Implemented empty text state - Created requests

---

src/stylesheets/_navigation.scss
src/views/partials/navigation.njk
src/views/profile.njk

This PR implements the profile page to display relevant user information. The profile page is accessed by a navigation link 'Account', and is only displayed on the nav bar if a user is signed in. The information on the page is only available if there is a user object.
We currently do not store organisation and role on the user object but this is a work in progress. If these are available (via user.organisation or user.role), then they are displayed, otherwise 'unavailable' is shown.

DMBM 143 - View user profile

---

public/javascripts/removeFilter.js
src/stylesheets/_moj_filter.scss
src/views/find.njk
src/views/layouts/base.njk

This PR implements the functionality to clear individual filters from the selected filters. 
The `removeFilter()` javascript function listens for a click event on each of the selected filters, finds the corresponding checked checkbox, removes the check and resubmits the search form to display relevant results without the selected filter.

DMBM-839 - Clear Single Filter

---

__tests__/learn.tests.ts
src/routes/learnRoutes.ts
src/views/learn/data-sharing-arrangements.njk
src/views/learn/data-sharing-questions.njk
src/views/learn/guidance-on-publish.njk
src/views/learn/main.njk

This PR adds a guidance on publish page based on the current prototype: https://dds-e2e.herokuapp.com/WIP/learn/articles/guidance-on-publish
I have reconciled some of the links in other learn pages as well.
nb: there are still some links within the learn pages that need to be reconciled once all of the learn pages have been completed

DMBM/834 - LEARN - Guidance on Publish

---

__tests__/find.test.ts
__tests__/findService.test.ts
src/app.ts
src/routes/findRoutes.ts
src/services/findService.ts

This PR ensures we are using the python api on the find page.
**Needs some discussion to align before merging.**
For example:
Multiple filters currently dont work using express default `organisationFilters=department-for-business-and-trade&organisationFilters=department-for-work-pensions` -> api call `query=&organisation=department-for-business-and-trade,department-for-work-pensions`
Searching `address` returns one result, searching `postcode` returns none.

Replace internals with apis

---

src/routes/learnRoutes.ts
src/routes/profileRoutes.ts
src/routes/supplierRoutes.ts
src/stylesheets/application.scss
src/views/supplier/accept-request.njk
src/views/supplier/decision.njk
src/views/supplier/declaration.njk
src/views/supplier/received-requests.njk
src/views/supplier/review-request.njk
src/views/supplier/review-summary.njk

As a supplier we now see requests made to the specific organisation that the acquirer wants to request data from, as an acquirer I want to request data from `Department of work and Pension`, I have done so.
As a supplier when reviewing "Received requests", we now see requests made to us in this instance as a supplier `under the organisation`: `Department of Work and Pensions`
We can see the `month`, in the dates have been formatted
As a supplier I click requestId 
I then see the request summary:
I can see the data from the request.
I can Click continue:
In this pr, click `Accept data share request`:
hit the declaration `static page`
further on to the `Request accepted page`
Currently this PR is without functionality to "sign off a ` received request` as `completed, accepted, rejected and …

Dmbm 844/manage data share completed and accepted

---

src/app.ts

"set up your routing so that requests for the JavaScript file are served from node_modules/govuk-frontend/govuk/all.js"
fixed this console error:

fix console error

---

src/views/resource.njk

This PR updates the frontend to use the updated metadata returned by the API in [this PR](https://github.com/co-cddo/data-marketplace-api/pull/24), (which Alasdair requested [here](https://tpximpact.slack.com/archives/C05F79AF7T3/p1694767000964429?thread_ts=1694766533.436699&cid=C05F79AF7T3))
If any related data assets are available in our database we now show a nicely-formatted link to the asset rather than a full URL.
E.g.

Display updated metadata

---

requests/requests.http.template
src/app.ts
src/middleware/ABACMiddleware.ts
src/routes/supplierRoutes.ts
src/views/supplier/received-requests.njk

This PR adds a new function which creates a middleware for calling the ABAC API endpoint.
The ABAC API endpoint needs to be called like this:
`GET {API}/users/permission/{target_type}/{target_id}/{action}`
where `target_type` is `asset` or `organisation`, `target_id` is the asset ID or organisation slug, and `action` is `READ`, `EDIT` or `REQUEST` for `target_type=asset`, or `CREATE_ASSET`, `VIEW_SHARE_REQUESTS` or `REVIEW_SHARE_REQUESTS` for `target_type=organisation`.
The `createAbacMiddleware` function takes `target_type` and `action`, determines `target_id` based on the logged in User or request path, and returns a function that can be used as middleware.
The middleware then just calls the ABAC API to check whether the user has the right permissions.
If the user does not have the …

DMBM-909: Permissions (and received-requests)

---

src/helperFunctions/formHelper.ts
src/routes/supplierRoutes.ts

This PR implements the acquirer journey of viewing a returned request with comments after making a share request. When an acquirer clicks on the Request ID of a returned request, they are taken to a page displaying comments made by the supplier as well as their original data share request answers in a static HTML format.
I have again made use of the checkAnswer form, where if the form verifies that the request is RETURNED, it doesn't display the 'change' button on the static answers page.

DMBM/843 - Request returned with comments

---

.github/workflows/test-lint.yaml
src/routes/acquirerRoutes.ts

After validation was run, the errorMessage wasnt emptied. This was trying to pass an object to the API which failed.
This PR's empties errorMessages for steps that pass validation

fixes odd bug persisting

---

package.json
src/helperFunctions/formHelper.ts
src/helperFunctions/stringHelpers.ts
src/middleware/apiMiddleware.ts
src/middleware/validateFormMiddleware.ts
src/routes/acquirerRoutes.ts
src/routes/supplierRoutes.ts
src/types/express.d.ts
src/views/acquirer/check.njk
src/views/acquirer/confirmation.njk
src/views/acquirer/created-request-outcome.njk
src/views/acquirer/created-request-view-full-request.njk
src/views/partials/receivedRequestReview.njk
src/views/supplier/received-request-outcome.njk

This PR alters the current implementation of displaying an acquirer's returned full request statically and instead directs the user to the `/check` page with the ability to change their answers and resubmit. The page also displays any decision notes given by the asset publisher who returned the request.
(Thanks @kjoshi for your help!!)

DMBM- 920 - View full returned request with ability to resubmit + view notes

---

src/stylesheets/_documentList.scss
src/stylesheets/_relatedData.scss

This PR addresses the styling issues that were happening when the 'Show More' button was cutting off the description, caused mostly by titles in the description's markdown. I have increased the line capacity so that it should compensate for any descriptions that have similar markdown. I have also removed some redundant styling.

DMBM-934 - Find accordion style issue

---

package-lock.json
package.json
src/routes/findRoutes.ts

This PR addresses the issues caused by markdown being displayed in the asset description/summary on the search results page (shown below).
I initially tried rendering the markdown but some of the markdown includes titles, which does not look good as a truncated description (shown below).
Instead, I have installed the [remove-markdown](https://www.npmjs.com/package/remove-markdown) package + corresponding [@types](https://www.npmjs.com/package/@types/remove-markdown) package and have called the `removeMd()` function on each resource's summary and description if there is one (shown below)

DMBM-937 - Remove markdown from search results' asset descriptions/summaries

---

src/views/error.njk

Minor PR adding the `two-thirds` width limit to the error pages.

BUG - Add width styling to error pages

---

src/views/find.njk
src/views/resource.njk

- Strip out the (o) from the Endpoint URL (o) header. It is now just Endpoint URL.
- Documentation link is now in the data available section instead of the further information section.
- If a modified date value doesn’t exist, we omit the row from the Further Information table and use the issued date for other places where we would rely on the modified date, but make it clear that it is the issued date. And vice versa, if the issued date isn't available, use the modified date in its place. In the scenario where neither are available, both are omitted.

Bugfixes - Dates & further information table

---

public/javascripts/searchBar.js
src/routes/findRoutes.ts
src/views/layouts/base.njk

This PR enables the user to click the little ‘x’ on the search bar component and revert the page back to its original state (search results without search term), whilst maintaining any filter parameters. This is implemented with custom JS that listens for any value in the search input and if there is none, to submit the search form again. This is a bit of a work around and I have done this approach because we cannot directly interact with the little 'x' button that appears with the search bar as that is part of the GOV design system components. The user has to click away from the search bar once the 'x' is clicked, but this behaviour also occurs on the [GOV.UK website](https://www.gov.uk/search/all?keywords=test&order=relevance)'s search bar too.

DMBM/954 - search bar 'x' button

---

src/views/supplier/received-request-outcome.njk

This PR fixes the styling/rendering issue with the `accepted-request` page showing the email as plain rendered text.
before:
after:
The accepted-request page now shows the email, if clicked - opens default email software

BUG FIX ACQUIRER - accepted-request not able to click/see email 

---

public/javascripts/searchBar.js

This PR addresses the console errors from the first implementation and is refactored to only re-display the results once the user has clicked away from the search input.

Refactor JS search bar script

---

src/routes/acquirerRoutes.ts
src/views/acquirer/confirmation.njk
src/views/layouts/base.njk
src/views/supplier/accept-request.njk
src/views/supplier/reject-request.njk
src/views/supplier/return-request.njk

In this PR we can now choose which page shows the backLink button. On the frontend, we can now add `{% set noBackLink = true %}` to specific pages (partials) which will render the .njk page with noBackLink.
See example "decision" page:
See example "confirmation" page:
Also note that the Continue button has been removed from the page.

Dmbm 951/removal of back link and nav buttons for confirmation pages

---

src/app.ts
src/routes/infoRoutes.ts
src/views/cookies.njk
src/views/partials/cookieBanner.njk
src/views/partials/footer.njk

This PR adds the content of cookie statements.

add cookie route and content

---

src/routes/publisherRoutes.ts
src/views/publisher/asset-error.njk
src/views/publisher/file_error.njk
src/views/publisher/total_error.njk
src/views/publisher/upload-summary.njk

After a user has uploaded a CSV, one of two things will happen:
a) The CSVs are unprocessable and they get redirected to an error page (currently very ugly just showing a json error)
b) The CSVs were processed by the API and we see the page that Amir wrote with a summary of all assets extracted from the files, but now it also has any errors in the table. So far, these do not link to the error detail pages but they soon will. Note that the asset type is missing from the table, as an unprocessed item doesn't have a type, and the ID is used instead of the name to identify it.

Add errors to upload summary

---

public/javascripts/linkStyling.js
src/views/find.njk
src/views/layouts/base.njk
src/views/resource.njk

This PR includes a script that adds the class `"govuk-link"` to any `<a>` tag in an asset's description. The descriptions we receive from partners may contain any kind of markdown which we render using nunjucks-markdown. Now, if there is an` <a>` tag, it will be styled the same as all the other links within the build.

DMBM/936 - Missing govuk-link styling on markdown links

---

src/routes/publisherRoutes.ts
src/views/publisher/csv_upload.njk
src/views/publisher/post_publish.njk
src/views/publisher/preview.njk
src/views/publisher/upload-summary.njk

This PR adds UI for the publisher journey, clicking 
on the Data Marketplace landing page
We are taken to:
The Values you see on the page here, will be hard coded:
clicking the `Add a new data description` will take you to this page:
which the user is able to download the template. When the user is satisfied, once they click `Publish from CSV` the user will then see this page:
it is important to note that this page is due to change, currently @kjoshi has implemented a fix in ("a branch yet to be made as a PR")
There will be one upload a file section, with reduced text.
Once the user has uploaded their files and hits the "Continue" button they then see the upload-summary page:
the user can click between the `Datasets` or `DataService` which will show the details from the uploaded CSV, …

Publisher UI

---

src/views/resource.njk

If the licence of an asset is set to the default value (if a value isn't provided when the data is loaded in), we display the text: 'Data share agreement required' and remove the link.

DMBM-980/ internal data licence link

---

package-lock.json
package.json

Soydaner spotted that the version of the `xlsx` library used for parsing the spreadsheets was out of date and had a security vulnerability
https://github.com/co-cddo/data-marketplace/security/dependabot/1
This PR upgrades `xlsx` to the latest version, by following these docs:
https://docs.sheetjs.com/docs/getting-started/installation/nodejs

Upgrade XLSX library version

---

package.json
src/routes/publisherRoutes.ts
src/views/publisher/asset-error.njk
src/views/publisher/publish-dashboard.njk

This PR makes some minor updates to UI to take into account the [corresponding validation fixes made to the API](https://github.com/co-cddo/data-marketplace-api/pull/41).
- Use `| safe` to display HTML in the validation error messages, because the API now returns links to the x-gov metadata model in some cases
- If `valid_options` are returned, show them in the table of errors.
- Also made some unrelated changes to the publish dashboard, to remove the hard-coded organisation name.

Validation fixes

---

src/views/publisher/upload-summary.njk

This PR addresses the issue described in [DMBM-1071](https://cddodatamarketplace.atlassian.net/browse/DMBM-1071).
Previously if a file was uploaded which did not contain any dataset or data service descriptions, the user was still shown the `Publish data asset description` button.
Now a user is shown an error and asked to try uploading a new file:

DMBM 1071: Empty file upload

---

src/middleware/backMiddleware.ts
src/routes/publisherRoutes.ts
src/views/publisher/publish-dashboard.njk

This PR adds functionality which calls the new API endpoint added in [this PR](https://github.com/co-cddo/data-marketplace-api/pull/47), to display correct numbers of published datasets and data services on the publish dashboard page
- Call the new API endpoint and pass the numbers of datasets and data services to the `publish-dashboard` template.
- Remove the statistics related to share requests from the publish dashboard.

Publish dashboard
